### ISSUE TITLE
Bug when setting fractional zoom (zoomSnap) option on map

### ISSUE THREAD

**Issue by asjustis** [windycom/API#32]
Hi guys,

First time posting an issue, not sure where is the quicker response. I originally posted the issue here: https://community.windy.com/topic/20752/bug-when-setting-fractional-zoom-zoomsnap?_=1654580746506

The issue is when I set the fractional zoom (zoomSnap: 0.1, zoom : 8.4, for example), the Windy layers get lost, including labels and others (temp, rain, clouds, etc. whatever is active). From the investigation, it seems the content is translated wrong. 
Maybe that's a bug in the API? Would there be any workaround that I can't see, maybe?

![Screenshot 2022-06-07 at 09 48 51](https://user-images.githubusercontent.com/1465112/172371310-f15773f3-5073-448c-841b-df71a64ec99f.png)

Some of the code I use for this:
```
windyInit(config.windyOptions, windyAPI => {

    const { map, colors, broadcast, store, picker, utils } = windyAPI;

    map.options.zoomSnap = 0.1;
    map.setZoom(8.4)
}
```

Thanks!
Justinas

**Comment by mdorda** [comment]
Hi, thanks for reporting the issue. I am affraid it is bug related to leaflet. We do not use fractial zoom at all at windy.com, because it was glitchy and we found out we do not need it. Maybe it is fixed in the latest leaflet version, but our API lib is compatible only with 1.4.x leaflet version. We are not currently planning to upgrade to the latest version of Leaflet. Only workaround is not to use fractial zooms at the moment, sorry for the complications.
